In [1]:
array_list= [1,2,3,4,5,6,7]
print(array_list)

[1, 2, 3, 4, 5, 6, 7]


In [2]:
array_list_2 =[[1,2,3,4,5],[7,2,9,0,7]]
print(array_list_2)


[[1, 2, 3, 4, 5], [7, 2, 9, 0, 7]]


In [3]:
import numpy as np

In [4]:
np_array_list = np.array(array_list_2)
print(np_array_list)

[[1 2 3 4 5]
 [7 2 9 0 7]]


In [5]:
list= np_array_list.reshape(5,2)
print(list)

[[1 2]
 [3 4]
 [5 7]
 [2 9]
 [0 7]]


In [6]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [11]:
np.linspace(0,10,5,endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.linspace(0,10,5,dtype=int)

array([ 0,  2,  5,  7, 10])

In [13]:
np.linspace(0,10,5,dtype=float)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.linspace(0,10,5,endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [16]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [17]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [18]:
np.random.rand(5,4)*10

array([[9.72213725, 8.28711809, 6.09534734, 2.74125416],
       [5.0826542 , 3.02954464, 2.12757894, 5.84458926],
       [6.17566564, 8.02481219, 1.66185808, 0.03199518],
       [2.06288243, 9.15048619, 6.54023666, 7.96544095],
       [2.68354904, 5.96498386, 2.99793512, 6.19688468]])

In [19]:
l1=np.random.randint(10,size=(10,5))
print(l1)
np.shape(l1)

[[8 1 3 7 8]
 [8 9 8 1 2]
 [2 8 6 2 8]
 [2 9 3 8 7]
 [3 0 9 4 1]
 [4 2 0 6 0]
 [6 9 4 1 6]
 [3 3 9 9 7]
 [4 2 7 8 2]
 [2 5 2 3 2]]


(10, 5)

In [20]:
array_list= [1,2,3,4,5,6,7]
np.size(array_list)

7

In [21]:
np.shape(array_list)

(7,)

In [22]:
list=[1.0,1.7,1.9]
np.dtype

numpy.dtype

In [23]:
my_arr = np.array([[2,5,8,9],[9,7,6,33]],dtype='float')
print(my_arr)
my_arr = my_arr.astype(int,copy=False)
print(my_arr.dtype)
print(my_arr)


[[ 2.  5.  8.  9.]
 [ 9.  7.  6. 33.]]
int32
[[ 2  5  8  9]
 [ 9  7  6 33]]


In [24]:
my_arr.tolist()

[[2, 5, 8, 9], [9, 7, 6, 33]]

In [25]:
arr = [1,2,3,4,5,6]

x = arr.copy()
arr[0] = 42

print(arr)


[42, 2, 3, 4, 5, 6]


In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)


[42  2  3  4  5]
